# Generated by Django 5.2 on 2025-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Username',
            field=models.CharField(default='default_user', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='first_name',
            field=models.CharField(default='First', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='last_name',
            field=models.CharField(default='last', max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='password',
            field=models.CharField(default='TempPass123!', max_length=128),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='password2',
            field=models.CharField(default='TempPass123!', max_length=128),
        ),
    ]
