# Generated by Django 5.2 on 2025-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0002_remove_mymodel_description_remove_mymodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='Username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='password2',
            field=models.CharField(max_length=128),
        ),
    ]
