# Generated by Django 5.2 on 2025-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0003_alter_mymodel_username_alter_mymodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='password2',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='first_name',
            field=models.CharField(default='First', max_length=100),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='last_name',
            field=models.CharField(default='last', max_length=100),
        ),
    ]
