# Generated by Django 5.2 on 2025-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0004_remove_mymodel_password2_alter_mymodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='password2',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
