# Generated by Django 5.2 on 2025-04-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0005_mymodel_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='password2',
        ),
    ]
