# Generated by Django 5.2 on 2025-04-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0006_remove_mymodel_password2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
